from setuptools import setup, find_packages


setup(
    name='zeit.content.quiz',
    version='0.5.13.dev0',
    author='gocept, Zeit Online',
    author_email='zon-backend@zeit.de',
    url='http://www.zeit.de/',
    description="vivi Content-Type Quiz",
    packages=find_packages('src'),
    package_dir={'': 'src'},
    include_package_data=True,
    zip_safe=False,
    license='BSD',
    namespace_packages=['zeit', 'zeit.content'],
    install_requires=[
        'gocept.form',
        'lxml',
        'rwproperty',
        'setuptools',
        'z3c.etestbrowser',
        'zc.form',
        'zeit.cms>=2.32.0.dev0',
        'zeit.content.quiz',
        'zeit.wysiwyg',
        'zope.annotation',
        'zope.app.container',
        'zope.app.pagetemplate',
        'zope.app.securitypolicy',
        'zope.app.zcmlfiles',
        'zope.cachedescriptors',
        'zope.component',
        'zope.event',
        'zope.formlib',
        'zope.interface',
        'zope.lifecycleevent',
        'zope.location',
        'zope.publisher',
        'zope.schema',
        'zope.security',
        'zope.testing',
        'zope.traversing',
    ],
    entry_points={
        'fanstatic.libraries': [
            'zeit_content_quiz=zeit.content.quiz.browser.resources:lib',
        ],
    },
)
